import type { ProcessGuide } from "./types";

export const mockGuides: ProcessGuide[] = [
  {
    id: "how-to-open-dashen-bank",
    title: "how to open dashen bank",
    category: "Bank Account Opening",
    institution: "Dashen Bank",
    region: "Ethiopia",
    language: "English",
    summary: "Quick starter guide for opening a Dashen Bank account.",
    prerequisites: ["Valid government-issued ID", "Initial deposit amount", "Active mobile number"],
    requiredDocuments: [
      "Government-issued ID (National ID/Passport)",
      "Recent passport-size photos",
      "Proof of address (if requested)",
    ],
    fees: "Usually no account opening fee; minimum opening balance may apply.",
    deadlines:
      "No strict deadline. Account can usually be opened the same day if documents are complete.",
    estimatedTime: "30-90 minutes",
    contactLinks: [
      {
        label: "Dashen Bank branch locator",
        url: "https://www.dashenbanksc.com/branches",
      },
    ],
    sourceType: "community-contributed",
    version: 1,
    updatedAt: "2026-04-25",
    steps: [
      {
        id: "dashen-open-step-1",
        title: "Prepare required documents",
        description:
          "Gather your ID, photos, and mobile number details before visiting the branch.",
        requiredDocuments: ["Government-issued ID", "Passport-size photos"],
        cost: "$0",
        expectedDuration: "10-20 minutes",
        actionMode: "offline",
        officeUrl: "https://www.dashenbanksc.com/branches",
        sourceReferenceUrl: "https://www.dashenbanksc.com/",
      },
      {
        id: "dashen-open-step-2",
        title: "Complete account opening form at branch",
        description:
          "Ask customer service for the form, fill it, and submit it with your documents.",
        requiredDocuments: ["Completed application form", "Government-issued ID"],
        cost: "$0",
        expectedDuration: "15-30 minutes",
        actionMode: "offline",
        officeUrl: "https://www.dashenbanksc.com/branches",
        sourceReferenceUrl: "https://www.dashenbanksc.com/",
      },
      {
        id: "dashen-open-step-3",
        title: "Make initial deposit and receive account details",
        description:
          "Deposit the required amount and collect your account number and activation details.",
        requiredDocuments: ["Deposit amount", "Approved account form"],
        cost: "Minimum deposit depends on account type",
        expectedDuration: "10-40 minutes",
        actionMode: "offline",
        officeUrl: "https://www.dashenbanksc.com/branches",
        sourceReferenceUrl: "https://www.dashenbanksc.com/",
      },
    ],
  },
  {
    id: "open-dashen-bank-account",
    title: "How to Open Dashen Bank Account",
    category: "Bank Account Opening",
    institution: "Dashen Bank",
    region: "Ethiopia",
    language: "English",
    summary: "Step-by-step guide for opening a new personal bank account at Dashen Bank.",
    prerequisites: ["Valid government-issued ID", "Initial deposit amount", "Active mobile number"],
    requiredDocuments: [
      "Government-issued ID (National ID/Passport)",
      "Recent passport-size photos",
      "Proof of address (if requested)",
    ],
    fees: "Usually no account opening fee; minimum opening balance may apply.",
    deadlines:
      "No strict deadline. Account can usually be opened the same day if documents are complete.",
    estimatedTime: "30-90 minutes",
    contactLinks: [
      {
        label: "Dashen Bank branch locator",
        url: "https://www.dashenbanksc.com/branches",
      },
    ],
    sourceType: "community-contributed",
    version: 1,
    updatedAt: "2026-04-25",
    steps: [
      {
        id: "dashen-step-1",
        title: "Prepare required documents",
        description:
          "Gather your ID, photos, and any supporting residence information before visiting the branch.",
        requiredDocuments: ["Government-issued ID", "Passport-size photos"],
        cost: "$0",
        expectedDuration: "10-20 minutes",
        actionMode: "offline",
        officeUrl: "https://www.dashenbanksc.com/branches",
        sourceReferenceUrl: "https://www.dashenbanksc.com/",
      },
      {
        id: "dashen-step-2",
        title: "Visit nearest Dashen Bank branch and fill account opening form",
        description:
          "Request an account opening form, complete it, and submit it to the customer service desk.",
        requiredDocuments: ["Completed application form", "Government-issued ID"],
        cost: "$0",
        expectedDuration: "15-30 minutes",
        actionMode: "offline",
        officeUrl: "https://www.dashenbanksc.com/branches",
        sourceReferenceUrl: "https://www.dashenbanksc.com/",
      },
      {
        id: "dashen-step-3",
        title: "Make initial deposit and activate account",
        description:
          "Deposit the required minimum balance, receive account details, and set up mobile/SMS alerts if available.",
        requiredDocuments: ["Deposit amount", "Approved account form"],
        cost: "Minimum deposit depends on account type",
        expectedDuration: "10-40 minutes",
        actionMode: "offline",
        officeUrl: "https://www.dashenbanksc.com/branches",
        sourceReferenceUrl: "https://www.dashenbanksc.com/",
      },
    ],
  },
  {
    id: "tax-filing-national-2026",
    title: "Annual Individual Tax Filing (Online)",
    category: "Tax Filing",
    institution: "National Revenue Authority",
    region: "National",
    language: "English",
    summary: "Guide for filing yearly personal taxes through the public portal.",
    prerequisites: ["Tax ID", "Online account", "Annual income records"],
    requiredDocuments: [
      "Government-issued ID",
      "Income statements",
      "Deduction receipts",
      "Bank account details",
    ],
    fees: "No filing fee for standard individual returns.",
    deadlines: "Submit before April 30 each year.",
    estimatedTime: "1-2 hours",
    contactLinks: [
      {
        label: "Revenue authority help center",
        url: "https://example.gov/revenue/help",
      },
    ],
    sourceType: "community-contributed",
    version: 2,
    updatedAt: "2026-03-12",
    steps: [
      {
        id: "tax-step-1",
        title: "Create or verify your tax portal account",
        description: "Log in to the tax portal and verify profile details before filing.",
        requiredDocuments: ["Tax ID", "Mobile number for OTP"],
        cost: "$0",
        expectedDuration: "10-15 minutes",
        actionMode: "online",
        officeUrl: "https://example.gov/revenue/portal",
        sourceReferenceUrl: "https://example.gov/revenue/account-guide",
      },
      {
        id: "tax-step-2",
        title: "Upload income and deduction records",
        description: "Fill in income sections and upload deduction evidence documents.",
        requiredDocuments: ["Income statements", "Deduction receipts"],
        cost: "$0",
        expectedDuration: "35-45 minutes",
        actionMode: "online",
        officeUrl: "https://example.gov/revenue/portal/returns",
        sourceReferenceUrl: "https://example.gov/revenue/deductions",
      },
      {
        id: "tax-step-3",
        title: "Review summary and submit return",
        description: "Check calculated tax amount and submit final declaration.",
        requiredDocuments: ["Bank account details"],
        cost: "$0",
        expectedDuration: "10-20 minutes",
        actionMode: "online",
        officeUrl: "https://example.gov/revenue/portal/submit",
        sourceReferenceUrl: "https://example.gov/revenue/filing-rules",
      },
    ],
  },
  {
    id: "driver-license-city-a",
    title: "Driver's License Registration (City A)",
    category: "Driver's License Registration",
    institution: "Department of Motor Vehicles",
    region: "City A",
    language: "English",
    summary: "Apply for first-time driver's license in City A jurisdiction.",
    prerequisites: ["Minimum age requirement", "Learner permit", "Vision test readiness"],
    requiredDocuments: [
      "Government-issued ID",
      "Proof of residence",
      "Learner permit",
      "Passport-sized photo",
    ],
    fees: "$35 application + $20 road test fee.",
    deadlines: "Complete road test within 6 months of application.",
    estimatedTime: "1-3 weeks",
    contactLinks: [
      {
        label: "DMV City A appointments",
        url: "https://example.gov/dmv/city-a/appointments",
      },
    ],
    sourceType: "community-contributed",
    version: 4,
    updatedAt: "2026-02-20",
    steps: [
      {
        id: "dl-a-step-1",
        title: "Book appointment",
        description: "Reserve your in-person DMV slot for document verification.",
        requiredDocuments: ["Government-issued ID"],
        cost: "$0",
        expectedDuration: "5-10 minutes",
        actionMode: "online",
        officeUrl: "https://example.gov/dmv/city-a/appointments",
        sourceReferenceUrl: "https://example.gov/dmv/city-a/how-to-book",
      },
      {
        id: "dl-a-step-2",
        title: "Submit documents at DMV office",
        description: "Attend the appointment with all required physical documents.",
        requiredDocuments: ["Proof of residence", "Learner permit", "Photo"],
        cost: "$35",
        expectedDuration: "30-60 minutes",
        actionMode: "offline",
        officeUrl: "https://example.gov/dmv/city-a/offices",
        sourceReferenceUrl: "https://example.gov/dmv/city-a/document-checklist",
      },
      {
        id: "dl-a-step-3",
        title: "Complete road test",
        description: "Take the practical driving test on your assigned date.",
        requiredDocuments: ["Learner permit", "Appointment slip"],
        cost: "$20",
        expectedDuration: "45-90 minutes",
        actionMode: "offline",
        officeUrl: "https://example.gov/dmv/city-a/road-tests",
        sourceReferenceUrl: "https://example.gov/dmv/city-a/road-test-rules",
      },
    ],
  },
  {
    id: "driver-license-city-b",
    title: "Driver's License Registration (City B Fast-track)",
    category: "Driver's License Registration",
    institution: "Department of Motor Vehicles",
    region: "City B",
    language: "English",
    summary: "Alternative guide for City B with integrated digital queue process.",
    prerequisites: ["Minimum age requirement", "Learner permit"],
    requiredDocuments: ["ID", "Proof of residence", "Learner permit"],
    fees: "$50 bundled fee.",
    deadlines: "Complete testing within 90 days of payment.",
    estimatedTime: "3-10 days",
    contactLinks: [
      {
        label: "DMV City B help desk",
        url: "https://example.gov/dmv/city-b/help",
      },
    ],
    sourceType: "community-contributed",
    version: 1,
    updatedAt: "2026-01-30",
    alternativeOf: "driver-license-city-a",
    steps: [
      {
        id: "dl-b-step-1",
        title: "Create fast-track queue token",
        description: "Generate your queue token through City B DMV portal.",
        requiredDocuments: ["ID", "Learner permit"],
        cost: "$10",
        expectedDuration: "10 minutes",
        actionMode: "online",
        officeUrl: "https://example.gov/dmv/city-b/queue",
        sourceReferenceUrl: "https://example.gov/dmv/city-b/queue-guide",
      },
      {
        id: "dl-b-step-2",
        title: "Verification and payment",
        description: "Verify documents in person and pay the remaining bundled fee.",
        requiredDocuments: ["Proof of residence", "Queue token"],
        cost: "$40",
        expectedDuration: "20-40 minutes",
        actionMode: "offline",
        officeUrl: "https://example.gov/dmv/city-b/offices",
        sourceReferenceUrl: "https://example.gov/dmv/city-b/payment-rules",
      },
      {
        id: "dl-b-step-3",
        title: "Schedule and complete driving assessment",
        description: "Use portal to schedule your assessment and attend at test center.",
        requiredDocuments: ["Payment receipt", "Learner permit"],
        cost: "$0",
        expectedDuration: "1-2 hours",
        actionMode: "offline",
        officeUrl: "https://example.gov/dmv/city-b/tests",
        sourceReferenceUrl: "https://example.gov/dmv/city-b/test-policy",
      },
    ],
  },
  {
    id: "business-permit-metropolitan",
    title: "Small Business Permit Registration",
    category: "Business Permit",
    institution: "City Business Office",
    region: "Metropolitan Region",
    language: "English",
    summary: "Step-by-step checklist to register and activate a small business permit.",
    prerequisites: ["Business name reservation", "Tax number", "Address lease/ownership"],
    requiredDocuments: [
      "Business name certificate",
      "Owner ID",
      "Tax registration",
      "Lease agreement",
      "Safety certificate",
    ],
    fees: "$120 permit fee + optional inspection fees.",
    deadlines: "Apply within 30 days of business opening.",
    estimatedTime: "1-2 weeks",
    contactLinks: [
      {
        label: "Business office support",
        url: "https://example.gov/business-office/support",
      },
    ],
    sourceType: "community-contributed",
    version: 3,
    updatedAt: "2026-04-05",
    steps: [
      {
        id: "bp-step-1",
        title: "Submit online pre-application",
        description: "Create permit request and upload initial ownership documents.",
        requiredDocuments: ["Owner ID", "Business name certificate"],
        cost: "$0",
        expectedDuration: "15-25 minutes",
        actionMode: "online",
        officeUrl: "https://example.gov/business-office/apply",
        sourceReferenceUrl: "https://example.gov/business-office/pre-application-guide",
      },
      {
        id: "bp-step-2",
        title: "On-site validation",
        description: "Visit city office for document validation and safety scheduling.",
        requiredDocuments: ["Tax registration", "Lease agreement"],
        cost: "$120",
        expectedDuration: "45-75 minutes",
        actionMode: "offline",
        officeUrl: "https://example.gov/business-office/locations",
        sourceReferenceUrl: "https://example.gov/business-office/validation-rules",
      },
      {
        id: "bp-step-3",
        title: "Receive permit and activate account",
        description: "Collect your permit certificate and activate business dashboard access.",
        requiredDocuments: ["Payment receipt", "Safety certificate"],
        cost: "$0",
        expectedDuration: "20-30 minutes",
        actionMode: "offline",
        officeUrl: "https://example.gov/business-office/permits",
        sourceReferenceUrl: "https://example.gov/business-office/activation-guide",
      },
    ],
  },
];
